/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
        "colors": {
            "surface-container-low": "#f2f4f6",
            "on-error-container": "#93000a",
            "outline": "#857461",
            "on-background": "#191c1e",
            "inverse-primary": "#ffb952",
            "on-primary-fixed-variant": "#633f00",
            "surface-container-lowest": "#ffffff",
            "secondary-fixed": "#d9e3f6",
            "on-secondary": "#ffffff",
            "surface-dim": "#d8dadc",
            "inverse-on-surface": "#eff1f3",
            "surface-container-high": "#e6e8ea",
            "on-tertiary-container": "#3d4754",
            "on-primary-fixed": "#291800",
            "on-surface": "#191c1e",
            "primary-fixed-dim": "#ffb952",
            "background": "#f7f9fb",
            "on-tertiary": "#ffffff",
            "surface": "#f7f9fb",
            "on-tertiary-fixed": "#121c28",
            "tertiary": "#555f6d",
            "on-tertiary-fixed-variant": "#3e4755",
            "surface-tint": "#825500",
            "on-primary": "#ffffff",
            "inverse-surface": "#2d3133",
            "on-error": "#ffffff",
            "outline-variant": "#d7c3ad",
            "on-secondary-container": "#596373",
            "primary": "#825500",
            "surface-container": "#eceef0",
            "secondary-container": "#d6e0f3",
            "tertiary-fixed-dim": "#bdc7d8",
            "surface-container-highest": "#e0e3e5",
            "surface-bright": "#f7f9fb",
            "primary-fixed": "#ffddb4",
            "on-surface-variant": "#524433",
            "error": "#ba1a1a",
            "secondary-fixed-dim": "#bdc7d9",
            "on-secondary-fixed-variant": "#3d4756",
            "primary-container": "#f5a300",
            "on-secondary-fixed": "#121c2a",
            "tertiary-fixed": "#d9e3f4",
            "surface-variant": "#e0e3e5",
            "error-container": "#ffdad6",
            "secondary": "#555f6f",
            "on-primary-container": "#623f00",
            "tertiary-container": "#abb5c5"
        },
        "borderRadius": {
            "DEFAULT": "0.25rem",
            "lg": "0.5rem",
            "xl": "0.75rem",
            "full": "9999px",
            "brand": "12px"
        },
        "spacing": {
            "element-gap": "16px",
            "container-padding-desktop": "32px",
            "section-gap": "64px",
            "unit": "4px",
            "gutter": "24px",
            "container-padding-mobile": "16px"
        },
        "fontFamily": {
            "body-sm": ["Inter"],
            "headline-sm": ["Inter"],
            "label-md": ["Inter"],
            "headline-lg": ["Inter"],
            "body-lg": ["Inter"],
            "display-lg": ["Inter"],
            "body-md": ["Inter"],
            "label-sm": ["Inter"],
            "headline-md": ["Inter"],
            "headline-lg-mobile": ["Inter"]
        },
        "fontSize": {
            "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
            "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
            "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
            "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
            "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
            "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
            "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
            "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
            "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
            "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}]
        }
    },
  },
  plugins: [],
}
