version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: git_recruitment_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: gituser
      POSTGRES_PASSWORD: gitpass
      POSTGRES_DB: git_recruitment
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: